import Head from "next/head";

import styled from "styled-components";

import Layout from "../components/Layout/Layout";
import Block from "../components/Block/Block";
import Wrap from "../components/Wrap/Wrap";
import Restaurants from "../components/Restaurants/Restaurants";
import HomeFilter from "../components/HomeFilter/HomeFilter";

export const LayoutWrapper = styled.div`
  display: flex;
  flex-grow: 1;

  @media (min-width: 768px) {
    align-items: flex-start;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Block>
          <Wrap>
            <LayoutWrapper>
              <HomeFilter />
              <Restaurants />
            </LayoutWrapper>
          </Wrap>
        </Block>
      </Layout>
    </>
  );
}
